apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "authdb"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:3001"
  BACKEND_SERVICE_URL: "http://backend-service:5000"
  
  # Application configuration
  NODE_ENV: "production"

